# print("Enter your name")
# name = input()
# print(f"Hey !! {name}, welcome to the party...")
# print('\n')
# print("<-------------Example 2-------------------->")
# print("Enter first number")
# a = int(input())
# print("Enter second number")
# b = int(input())
# print(f"sum of {a} and {b} is {a+b}")
# print('\n')
# # String formatting using format() method
# print("<--------Default order------------>")
# str1 = "{} {} {}".format("Travelling", 'is', 'life')
# print("String will be printed in default order:")
# print(str1)
# print("<--------Positional formatting------------>")
# str2 = "{1} {2} {0}".format("love", "Travelling", "is")
# print(str2)
# print("<--------Keyword formatting------------>")
# str3 = "{T} {i} {l}".format(T='Travelling', l='love', i='is')
# print(str3)
# print('\n')
# # String formatting using % operator
# print("Enter number of items")
# item = int(input())
# print("%s is carrying %d items" % (name, item))

print(num1 > num2) or (num3 > num4)
